if(NOT DEFINED EXECUTABLE OR NOT METHOD MATCHES "^(Penalty|Semismooth)$")
    message(FATAL_ERROR "EXECUTABLE and METHOD are required")
endif()
string(TOLOWER "${METHOD}" method)
function(measure text label result)
    string(REGEX MATCH "${label}: ([0-9.eE+-]+)" match "${text}")
    if(NOT match)
        message(FATAL_ERROR "Missing diagnostic ${label}")
    endif()
    set(${result} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()
foreach(material IN ITEMS elastic high-yield yielding)
    set(args --material elastic)
    if(material STREQUAL "high-yield")
        set(args --material j2 --yield-stress 1000000)
    elseif(material STREQUAL "yielding")
        set(args --material j2 --yield-stress 1 --hardening-modulus 100)
    endif()
    execute_process(COMMAND "${EXECUTABLE}" "--${method}" --load-path load-return
        -nx 2 -ny 2 -steps 8 -no-output ${args}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
    if(NOT result STREQUAL "0" OR NOT output MATCHES "${METHOD} contact verification: passed")
        message(FATAL_ERROR "${material} failed (${result}): ${output}\n${error}")
    endif()
    measure("${output}" "Final displacement infinity norm" displacement)
    measure("${output}" "Maximum committed equivalent plastic strain \\(cell average\\)" plasticity)
    measure("${output}" "Peak contact pressure" pressure)
    measure("${output}" "Maximum bottom displacement error" boundary_error)
    if(boundary_error GREATER 1e-7 OR NOT pressure GREATER 0)
        message(FATAL_ERROR "Missing peak contact or nonzero final driven boundary")
    endif()
    if(material STREQUAL "yielding")
        if(displacement LESS 0.004 OR displacement GREATER 0.009 OR plasticity LESS 0.005 OR plasticity GREATER 0.012)
            message(FATAL_ERROR "Expected permanent deformation: u=${displacement}, ep=${plasticity}")
        endif()
    else()
        if(displacement GREATER 1e-5 OR plasticity GREATER 1e-7)
            message(FATAL_ERROR "Expected elastic recovery: u=${displacement}, ep=${plasticity}")
        endif()
        # Compare peak response, not only the trivially zero return state.
        # Compare scientific mantissas to 0.01%, requiring the same exponent.
        if(material STREQUAL "elastic")
            set(elastic_pressure "${pressure}")
        else()
            string(REGEX MATCH "([1-9])\\.([0-9]+)e([+-][0-9]+)" match "${elastic_pressure}")
            set(elastic_mantissa "${CMAKE_MATCH_1}${CMAKE_MATCH_2}")
            set(elastic_exponent "${CMAKE_MATCH_3}")
            string(REGEX MATCH "([1-9])\\.([0-9]+)e([+-][0-9]+)" match "${pressure}")
            set(high_yield_mantissa "${CMAKE_MATCH_1}${CMAKE_MATCH_2}")
            set(high_yield_exponent "${CMAKE_MATCH_3}")
            math(EXPR difference "${high_yield_mantissa} - ${elastic_mantissa}")
            math(EXPR tolerance "${elastic_mantissa} / 10000")
            math(EXPR negative_tolerance "-${tolerance}")
            if(NOT elastic_exponent STREQUAL high_yield_exponent OR
               difference GREATER tolerance OR difference LESS negative_tolerance)
                message(FATAL_ERROR "High-yield peak pressure differs: ${elastic_pressure} vs ${pressure}")
            endif()
        endif()
    endif()
    message(STATUS "${METHOD} ${material}: residual u=${displacement}, ep=${plasticity}, peak p=${pressure}")
endforeach()
