if(NOT DEFINED EXECUTABLE OR NOT DEFINED TEST_DIRECTORY OR NOT METHOD MATCHES "^(Penalty|Semismooth)$")
    message(FATAL_ERROR "Output verification requires EXECUTABLE, TEST_DIRECTORY, and METHOD (Penalty or Semismooth).")
endif()

string(TOLOWER "${METHOD}" method)
set(collections "${method}_contact" "${method}_contact_obstacle")
if(METHOD STREQUAL "Semismooth")
    list(APPEND collections semismooth_contact_multiplier)
endif()
# A fresh, test-owned directory makes collisions reproducible even when run as root.
file(REMOVE_RECURSE "${TEST_DIRECTORY}")
file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
foreach(blocked IN ITEMS none prefix ${collections})
    set(directory "${TEST_DIRECTORY}/${blocked}")
    file(MAKE_DIRECTORY "${directory}")
    set(prefix "${directory}/output")
    if(blocked STREQUAL "prefix")
        file(WRITE "${prefix}" "This file deliberately blocks the output directory.\n")
    elseif(NOT blocked STREQUAL "none")
        file(MAKE_DIRECTORY "${prefix}")
        file(WRITE "${prefix}/${blocked}" "This file deliberately blocks a collection directory.\n")
    endif()
    execute_process(
        COMMAND "${EXECUTABLE}" "--${method}" -nx 2 -ny 2 -steps 8
            --load-path load-return --material j2 --yield-stress 1 --hardening-modulus 100
            -output -odir "${prefix}"
        WORKING_DIRECTORY "${directory}"
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error
        TIMEOUT 120
    )
    if(NOT blocked STREQUAL "none")
        if(NOT result STREQUAL "3" OR NOT error MATCHES "ParaView output failed for"
           OR output MATCHES "ParaView (body|multiplier|obstacle):|contact verification: passed")
            message(FATAL_ERROR "${METHOD} did not report output failure for ${blocked} (${result}):\n${output}\n${error}")
        endif()
        continue()
    endif()
    if(NOT result STREQUAL "0" OR NOT output MATCHES "${METHOD} contact verification: passed")
        message(FATAL_ERROR "${METHOD} positive output run failed (${result}):\n${output}\n${error}")
    endif()
    foreach(collection IN LISTS collections)
        set(pvd "${prefix}/${collection}/${collection}.pvd")
        if(NOT EXISTS "${pvd}")
            message(FATAL_ERROR "Missing collection ${pvd}")
        endif()
        file(READ "${pvd}" pvd_text)
        if(NOT pvd_text MATCHES "</VTKFile>")
            message(FATAL_ERROR "Incomplete collection ${pvd}")
        endif()
        string(REGEX MATCHALL "file=\"[^\"]+\"" datasets "${pvd_text}")
        if(NOT datasets)
            message(FATAL_ERROR "No datasets in ${pvd}")
        endif()
        if(NOT collection MATCHES "_obstacle$")
            list(LENGTH datasets count)
            if(count LESS 17 OR NOT pvd_text MATCHES "timestep=\"0\"" OR NOT pvd_text MATCHES "timestep=\"2\"")
                message(FATAL_ERROR "Missing initial/accepted/return frames in ${pvd}")
            endif()
        endif()
        foreach(dataset IN LISTS datasets)
            string(REGEX REPLACE "^file=\"|\"$" "" relative_path "${dataset}")
            set(pvtu "${prefix}/${collection}/${relative_path}")
            file(READ "${pvtu}" pvtu_text)
            if(NOT pvtu_text MATCHES "</VTKFile>")
                message(FATAL_ERROR "Incomplete parallel dataset ${pvtu}")
            endif()
            get_filename_component(cycle_directory "${pvtu}" DIRECTORY)
            string(REGEX MATCHALL "Source=\"[^\"]+\"" pieces "${pvtu_text}")
            if(NOT pieces)
                message(FATAL_ERROR "No pieces in ${pvtu}")
            endif()
            foreach(piece IN LISTS pieces)
                string(REGEX REPLACE "^Source=\"|\"$" "" relative_path "${piece}")
                file(READ "${cycle_directory}/${relative_path}" vtu_text)
                if(NOT vtu_text MATCHES "</VTKFile>")
                    message(FATAL_ERROR "Incomplete VTU piece ${cycle_directory}/${relative_path}")
                endif()
                if(collection STREQUAL "${method}_contact")
                    if(NOT vtu_text MATCHES "Name=\"equivalent_plastic_strain\""
                       OR NOT vtu_text MATCHES "Name=\"displacement\" NumberOfComponents=\"3\"")
                        message(FATAL_ERROR "Missing plastic strain or 3-component warp vector")
                    endif()
                endif()
                if(collection MATCHES "_multiplier$" AND NOT vtu_text MATCHES "Name=\"boundary_multiplier\"")
                    message(FATAL_ERROR "Missing multiplier field in ${collection}")
                elseif(collection STREQUAL "${method}_contact" AND NOT vtu_text MATCHES "Name=\"displacement\"")
                    message(FATAL_ERROR "Missing displacement field in ${collection}")
                endif()
            endforeach()
        endforeach()
    endforeach()
endforeach()
message(STATUS "${METHOD} contact output verified: datasets and expected failures.")
